### ISSUE TITLE
Architect builder is not compatible with Angular 8

### ISSUE THREAD

**Issue by WilhelmOlejnik** [martinroob/ngx-i18nsupport#136]
In Angular 8 architect API has changed and extracting i18n results in error.
https://docs.google.com/document/d/1SpN_2XEooI9_CPjqspAcNEBjVY874OWPZqOenjuF0qo

Tested it using CLI v.8.0.0-rc.4

1. `ng new i18test`
2. `ng add @ngx-i18nsupport/tooling --project=i18test --i18nFormat=xlf2 --languages=en,de,ru`
3. `ng xi18n i18test --i18n-format xlf2 --output-path i18n --i18n-locale en && ng run i18test:xliffmerge`

```
Could not find the implementation for builder @ngx-i18nsupport/tooling:xliffmerge
Error: Could not find the implementation for builder @ngx-i18nsupport/tooling:xliffmerge
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (C:\Users\wilhelmolejnik\Desktop\sandbox\i18test\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:49:19)
    at RunCommand.runSingleTarget (C:\Users\wilhelmolejnik\Desktop\sandbox\i18test\node_modules\@angular\cli\models\architect-command.js:176:55)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**Comment by martinroob** [comment]
Yes I am aware of this. There is already a branch to solve it when ng 8 is available (should come this week).
The architect support in ng 7 was experimental and undocumented and they incompatible changed it in 8.
In ng 8 they now start to have an official and documented API (although the documentation is far away from being good).

**Comment by timminss** [comment]
Thanks for the fantastic project Martin. It looks like Angular 8 has been released at this point. Any idea when the feature-ng8 branch will be merged? I'm having the same problem Wilhelm described above unfortunately. Cheers!

**Comment by martinroob** [comment]
publish version 8.0.0 of tooling
