### ISSUE TITLE
Cannot find module '@ngx-i18nsupport/ngx-i18nsupport-lib'

### ISSUE THREAD

**Issue by Pitros** [martinroob/ngx-i18nsupport#142]
I'm running Angular 7 and after installation using `ng add` and trying to run using `run projectname:xliffmerge` an error shows up:

```
Cannot find module '@ngx-i18nsupport/ngx-i18nsupport-lib'
Error: Cannot find module '@ngx-i18nsupport/ngx-i18nsupport-lib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at ...\node_modules\@ngx-i18nsupport\ngx-i18nsupport\bundles\ngx-i18nsupport-ngx-i18nsupport.umd.js:2:180
    at Object.<anonymous> (...\node_modules\@ngx-i18nsupport\ngx-i18nsupport\bundles\ngx-i18nsupport-ngx-i18nsupport.umd.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (...\node_modules\@ngx-i18nsupport\tooling\src\builders\src\xliffmergebuilder\xliffmerge.builder.js:11:27)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
```

Tried addding all dependencies without success
```
    "@ngx-i18nsupport/tooling": "^1.1.3",
    "@ngx-i18nsupport/ngx-i18nsupport": "^1.1.3",
    "@ngx-i18nsupport/ngx-i18nsupport-lib": "^1.12.0",
```

**Comment by torresdaniel11** [comment]
> I'm running Angular 7 and after installation using `ng add` and trying to run using `run projectname:xliffmerge` an error shows up:
> 
> ```
> Cannot find module '@ngx-i18nsupport/ngx-i18nsupport-lib'
> Error: Cannot find module '@ngx-i18nsupport/ngx-i18nsupport-lib'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
>     at Module.require (internal/modules/cjs/loader.js:636:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at ...\node_modules\@ngx-i18nsupport\ngx-i18nsupport\bundles\ngx-i18nsupport-ngx-i18nsupport.umd.js:2:180
>     at Object.<anonymous> (...\node_modules\@ngx-i18nsupport\ngx-i18nsupport\bundles\ngx-i18nsupport-ngx-i18nsupport.umd.js:5:2)
>     at Module._compile (internal/modules/cjs/loader.js:688:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
>     at Module.load (internal/modules/cjs/loader.js:598:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
>     at Module.require (internal/modules/cjs/loader.js:636:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (...\node_modules\@ngx-i18nsupport\tooling\src\builders\src\xliffmergebuilder\xliffmerge.builder.js:11:27)
>     at Module._compile (internal/modules/cjs/loader.js:688:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
> ```
> 
> Tried addding all dependencies without success
> 
> ```
>     "@ngx-i18nsupport/tooling": "^1.1.3",
>     "@ngx-i18nsupport/ngx-i18nsupport": "^1.1.3",
>     "@ngx-i18nsupport/ngx-i18nsupport-lib": "^1.12.0",
> ```

i'm having the same exact problem

**Comment by soft-aliimran** [comment]
Facing the exactly same issue with Angular 8

"@ngx-i18nsupport/tooling": "^8.0.2",
"@ngx-i18nsupport/ngx-i18nsupport": "^1.1.5",

**Comment by xavierclotet** [comment]
Me also the exact problem with Angular 7.2.15

**Comment by martinroob** [comment]
Something went wrong with the publishing. Will try to fix it in the next few days. Sorry about that.
