### ISSUE TITLE
0.7.1 run breaks with Exception

### ISSUE THREAD

**Issue by martinroob** [martinroob/ngx-i18nsupport#38]
TypeError: Cannot read property 'map' of undefined
    at XliffMerge.processLanguage (S:\experimente\tiny-translator\node_modules\ngx-i18nsupport\dist\xliffmerge\xliff-merge.js:220:13)
    at S:\experimente\tiny-translator\node_modules\ngx-i18nsupport\dist\xliffmerge\xliff-merge.js:132:49

**Comment by martinroob** [comment]
Errors occurs in the case of "file is up to date". Wrong return value in this case.
