### ISSUE TITLE
Unexpected token in JSON

### ISSUE THREAD

**Issue by doomslock** [martinroob/ngx-i18nsupport#43]
Hi,

I'm trying to use the xliffmerge tool with the profile but get the error below, am I doing something wrong?
I'm using the lastest version v0.7.4

>xliffmerge --profile xliffmerge.json

undefined:1
﻿{
^

SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at XliffMergeParameters.readProfile (C:\Users\Username\AppData\Roaming\npm\node_modules\ngx-i18nsupport\dist\xliffmerge\xliff-merge-parameters.js:76:21)
    at XliffMergeParameters.configure (C:\Users\Username\AppData\Roaming\npm\node_modules\ngx-i18nsupport\dist\xliffmerge\xliff-merge-parameters.js:37:35)
    at Function.XliffMergeParameters.createFromOptions (C:\Users\Username\AppData\Roaming\npm\node_modules\ngx-i18nsupport\dist\xliffmerge\xliff-merge-parameters.js:24:20)
    at XliffMerge.doRun (C:\Users\Username\AppData\Roaming\npm\node_modules\ngx-i18nsupport\dist\xliffmerge\xliff-merge.js:107:77)
    at XliffMerge.run (C:\Users\Username\AppData\Roaming\npm\node_modules\ngx-i18nsupport\dist\xliffmerge\xliff-merge.js:87:14)
    at Function.XliffMerge.main (C:\Users\Username\AppData\Roaming\npm\node_modules\ngx-i18nsupport\dist\xliffmerge\xliff-merge.js:29:85)
    at Object.<anonymous> (C:\Users\Username\AppData\Roaming\npm\node_modules\ngx-i18nsupport\dist\xliffmerge\main.js:8:26)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

xliffmerge.json:
```
{
  "xliffmergeOptions": {
    "srcDir": "src/i18n",
    "genDir": "src/i18n",
    "i18nFile": "messages.xlf",
    "i18nFormat": "xlf",
    "encoding": "UTF-8",
    "defaultLanguage": "en",
    "languages": [ "en", "nl", "fr", "de" ],
    "removeUnusedIds": true,
    "supportNgxTranslate": true,
    "useSourceAsTarget": false,
    "autotranslate": false,
    "apikey": "",
    "apikeyfile": "",
    "verbose": false,
    "quiet": false
  }
}
```

**Comment by martinroob** [comment]
At first look everything looks OK.  Maybe (just a guess) there is a strange char like a BOM at the beginning of your configuration file????

**Comment by BnSmth** [comment]
I am also having this problem

> xliffmerge -p translations.conf.json

```
undefined:1
﻿{
^

SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at XliffMergeParameters.readProfile (C:\Users\ben.smith\AppData\Roaming\npm\node_modules\ngx-i18nsupport\dist\xliffmerge\xliff-merge-parameters.js:77:21)
    at XliffMergeParameters.configure (C:\Users\ben.smith\AppData\Roaming\npm\node_modules\ngx-i18nsupport\dist\xliffmerge\xliff-merge-parameters.js:38:35)
    at Function.XliffMergeParameters.createFromOptions (C:\Users\ben.smith\AppData\Roaming\npm\node_modules\ngx-i18nsupport\dist\xliffmerge\xliff-merge-parameters.js:25:20)
    at XliffMerge.doRun (C:\Users\ben.smith\AppData\Roaming\npm\node_modules\ngx-i18nsupport\dist\xliffmerge\xliff-merge.js:109:77)
    at XliffMerge.run (C:\Users\ben.smith\AppData\Roaming\npm\node_modules\ngx-i18nsupport\dist\xliffmerge\xliff-merge.js:89:14)
    at Function.XliffMerge.main (C:\Users\ben.smith\AppData\Roaming\npm\node_modules\ngx-i18nsupport\dist\xliffmerge\xliff-merge.js:31:85)
    at Object.<anonymous> (C:\Users\ben.smith\AppData\Roaming\npm\node_modules\ngx-i18nsupport\dist\xliffmerge\main.js:8:26)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
```

With configuration file:
```
{
  "xliffmergeOptions": {
    "srcDir": "src/locale",
    "genDir": "src/locale",
    "i18nFormat": "xlf",
    "defaultLanguage": "en",
    "languages": [ "en", "de" ]
  }
```

Any help would be greatly appreciated. If I can get the script working it will be a god send! Thanks in advance.

**Comment by BnSmth** [comment]
I figured out what was causing this issue for me. When I copied in the example json config file into my own solution, the encoding of the file was set to UTF-8 with BOM. Changing the encoding to just UTF-8 resolved the issue. Great work on this project, it saved me a bunch of time!

**Comment by doomslock** [comment]
It was the same for me, thanks for the help!

**Comment by martinroob** [comment]
You are welcome
