### ISSUE TITLE
xliffmerge fails when ICU message contains interpolation and/or tags

### ISSUE THREAD

**Issue by krassx** [martinroob/ngx-i18nsupport#83]
The following expression
```
<source>{VAR_PLURAL, plural, =1 {Crash <x id="INTERPOLATION" equiv-text="{{ activity.options.merged_string }}"/> was} other {Crashes <x id="INTERPOLATION" equiv-text="{{ activity.options.merged_string }}"/> were} }</source>
```
causes xliffmerge to fail with

```
non ICU message:  {VAR_PLURAL, plural, =1 {Crash <x id="INTERPOLATION" equiv-text="{{ activity.options.merged_string }}"/> was} other {Crashes <x id="INTERPOLATION" equiv-text="{{ activity.options.merged_string }}"/> were} } Error: Error parsing ICU Message: expected EOF, found TEXT ("/> was} other ) (message {VAR_PLURAL, plural, =1 {Crash <x id="INTERPOLATION" equiv-text="{{ activity.options.merged_string }}"/> was} other {Crashes <x id="INTERPOLATION" equiv-text="{{ activity.options.merged_string }}"/> were} })
    at ParsedMessagePartICUMessage.expectNext (/Users/builder/app/node_modules/ngx-i18nsupport-lib/bundles/ngx-i18nsupport-lib.umd.js:6321:19)
    at ParsedMessagePartICUMessage.parseICUMessage (/Users/builder/app/node_modules/ngx-i18nsupport-lib/bundles/ngx-i18nsupport-lib.umd.js:6310:14)
    at new ParsedMessagePartICUMessage (/Users/builder/app/node_modules/ngx-i18nsupport-lib/bundles/ngx-i18nsupport-lib.umd.js:6262:15)
    at ParsedMessage.addICUMessage (/Users/builder/app/node_modules/ngx-i18nsupport-lib/bundles/ngx-i18nsupport-lib.umd.js:6033:26)
    at XliffMessageParser.AbstractMessageParser.addPartsOfNodeToMessage (/Users/builder/app/node_modules/ngx-i18nsupport-lib/bundles/ngx-i18nsupport-lib.umd.js:1446:29)
    at XliffMessageParser.AbstractMessageParser.createNormalizedMessageFromXML (/Users/builder/app/node_modules/ngx-i18nsupport-lib/bundles/ngx-i18nsupport-lib.umd.js:1409:18)
    at XliffTransUnit.createSourceContentNormalized (/Users/builder/app/node_modules/ngx-i18nsupport-lib/bundles/ngx-i18nsupport-lib.umd.js:5057:41)
    at XliffTransUnit.AbstractTransUnit.sourceContentNormalized (/Users/builder/app/node_modules/ngx-i18nsupport-lib/bundles/ngx-i18nsupport-lib.umd.js:1041:50)
    at /Users/builder/app/node_modules/ngx-i18nsupport/dist/autotranslate/xliff-merge-auto-translate-service.js:55:105
    at Array.filter (<anonymous>)
```

**Comment by martinroob** [comment]
This obviously is a bug too. Will work on it.
